### ISSUE TITLE
Set Show times

### ISSUE THREAD

**Issue by Fitzy1611** [whitesoup12/remote-falcon#100]
Issue: Having to set scripts to tur on and off Viewer control.

Potential Solution: in the screen that allows you to toggle on the viewer control, be able to set a time to turn on and a time to turn off viewer control. of course, this would have to be on any given day, 

it would make set up so much simpler for those who are not as program Savey.

**Comment by whitesoup12** [comment]
You can schedule any of the Remote Falcon commands in FPP. There's no need for a schedule in RF since FPP already has this functionality.

**Comment by Fitzy1611** [comment]
Sorry, I have searched and was unable to find how to do this, can you point me in the correct direction? new to all this.

**Comment by whitesoup12** [comment]
Here's the docs on the different commands you can use. https://docs.remotefalcon.com/docs/fpp-plugin/fpp-plugin-setup#remote-falcon-commands. To use them, simply go to your Schedules page in FPP, create a new entry, select Command as the entry type being run, then select the RF command you want to use.

**Comment by Fitzy1611** [comment]
perfect, thanks mate, sorry for the confusion. and appreciate the help.

**Comment by whitesoup12** [comment]
No worries at all. I'll leave this open for a bit in case you have any other questions.

**Comment by Fitzy1611** [comment]
git it all working thanks again.
