### ISSUE TITLE
Adding Item to Jukebox Messages Getting Lost at the Bottom of the Song List

### ISSUE THREAD

**Issue by bmasella** [whitesoup12/remote-falcon#101]
**Is your feature request related to a problem? Please describe:**
If you have a long song list and a guest taps on a song to add it to the jukebox they are not seeing the message because it is displaying at the bottom of the list of songs... So if you have a queue depth limit set to 3 or 4 the users never see the message as to why their song was not added to the queue.

**Describe the solution you'd like:**
Rather than at the bottom of the list of songs do a popup that displays the error text.

**Comment by whitesoup12** [comment]
Take a look at the styling in On Air template. It displays the message in the center of the page.

**Comment by bmasella** [comment]
Styling fiixes it... thanks
