### ISSUE TITLE
{QUEUE_SIZE} is not being rendered...

### ISSUE THREAD

**Issue by bmasella** [whitesoup12/remote-falcon#102]
**Your Show Name:**
depoebaylights

**Describe the bug:**
I have this html:  <div class="jukebox-title"># Selected Songs</div>
    <div class="body_text"> {QUEUE_SIZE} of {QUEUE_DEPTH} </div> and it displays as: # Selected Songs
{QUEUE_SIZE} of 3

**To Reproduce:**
See above

**Expected behavior:**
Queue_size to represent the number of songs already selected so if 1 song had been selected it would show 1 of 3 if 2 selected 2 of 3...etc.

**Comment by whitesoup12** [comment]
You HTML looks like this...

```
<div class="body_text"> {QUEUE_SIZE} of {QUEUE_DEPTH} </div>
```

This won't work because the HTML to React parser cannot parse 2 tags in the same line. Instead, try putting each tag in its own element, like this...

```
<div class="body_text"><span>{QUEUE_SIZE}</span> of <span>{QUEUE_DEPTH}</span></div>
```
