### ISSUE TITLE
Queue shows actual file name not the display name

### ISSUE THREAD

**Issue by ljbrusta** [whitesoup12/remote-falcon#107]
**Your Show Name:**
LightOfSilverhills

**Describe the bug:**
Now playing and queue shows the actual file name of the sequence instead of the Sequence display name even though all display names are set in the sequence settings page.

**To Reproduce:**
1. Request a song in jukebox mode
2. It shows the file name not the display name.

**Expected behavior:**
should show display name always

**Screenshots:**
![image](https://github.com/whitesoup12/remote-falcon/assets/47700342/53f65fbc-1deb-4e82-8a6c-a5810be40bc3)

**Desktop (if issue is seen on desktop, otherwise N/A):**
 - OS: [e.g. Windows]

**Smartphone (if issue is seen on mobile, otherwise N/A):**

**Comment by ljbrusta** [comment]
![Screenshot_20231126_203951_Chrome](https://github.com/whitesoup12/remote-falcon/assets/47700342/96afabe1-af09-4252-bbfb-8e34930766bd)

When requests are in it shows the displays name until it go to now playing.

**Comment by ljbrusta** [comment]
Ok I think I see the issue. If the name has a dot other than the frequency extension it doesn't know how to associate the name with the display name. To work around this so it looks professional again I'm going to remove all the version numbers from my files this is going to cause some extensive work but I need to have it look right going in to the coming days.

**Comment by ljbrusta** [comment]
Related to #63

**Comment by whitesoup12** [comment]
Yeah, workaround right now is to just remove dots form the sequence names.. I've had to do it myself.
