### ISSUE TITLE
Feature: Status Page

### ISSUE THREAD

**Issue by asherry99** [whitesoup12/remote-falcon#123]
**Is your feature request related to a problem? Please describe:**
When there's an outage (or even if there's not 😂 ) it feels like a lot of people scramble in the FB group to see if RF is down. 

**Describe the solution you'd like:**
A status page (bonus points one that lets you subscribe to updates via email, sms alerts) could help reduce the chaos and provide peace of mind as people can check to know if there is a known outage / issue. There's a lot of open source options out there, some even having built in health checks for monitoring. But this would have an extra cost of another container/instance running for you. 

Anyways just a suggestion, feel free to close if not desired. I really appreciate all the work you do!

**Comment by whitesoup12** [comment]
Turns out I already had one, lol.  https://remote-falcon.instatus.com/

Also created a webhook to send alerts to the Discord server, but you can set up your own alerts as well from the status page.

**Comment by asherry99** [comment]
Thank you!
