### ISSUE TITLE
docker compose up is failing

### ISSUE THREAD

**Issue by kentstroker** [whitesoup12/remote-falcon#125]
I have been trying to stand up my own service for the Xmas season given the recent rash of outages.

However, both the Docker compose method fails to compile.

When it gets to the npm run build step, the following errors get thrown.

Creating an optimized production build...
54.07 One of your dependencies, babel-preset-react-app, is importing the
54.07 "@babel/plugin-proposal-private-property-in-object" package without
54.07 declaring it in its dependencies. This is currently working because
54.07 "@babel/plugin-proposal-private-property-in-object" is already in your
54.07 node_modules folder for unrelated reasons, but it may break at any time.
54.07
54.07 babel-preset-react-app is part of the create-react-app project, which
54.07 is not maintianed anymore. It is thus unlikely that this bug will
54.07 ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
54.07 your devDependencies to work around this error. This will make this message
54.07 go away.
54.07
57.45 Failed to compile.
57.45
57.45 Module not found: Error: Can't resolve 'react/jsx-runtime' in '/app/node_modules/react-datadog/dist/esm'
57.45 Did you mean 'jsx-runtime.js'?
57.45 BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
57.45 (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
57.45 The extension in the request is mandatory for it to be fully specified.
57.45 Add the extension to the request.

The babel error seems workaround'able. But the jsx-runtime seems more problematic. I have been looking in the src folder to try and find this particular entry, I have yet to find it and even if I do, not entirely clear and what to do.

**Comment by whitesoup12** [comment]
This is related to npm and not RF, so you're not going to see this stuff directly in src. Have you tried Googling the error?
