### ISSUE TITLE
syslog filling up with tons of the same error

### ISSUE THREAD

**Issue by Jchuchla** [whitesoup12/remote-falcon#136]
**Your Show Name:**
ChuchlaFamilyLights

**Describe the bug:**
my /var/log/syslog is filling up with thousands of instances of the same error.  It logs roughly once per second.  

`Dec 10 22:59:50 fppMaster fppd_boot_post[2019]: PHP Notice:  Undefined property: stdClass::$sequenceName in /home/fpp/media/plugins/remote-falcon/remote_falcon_listener.php on line 234`

**To Reproduce:**
FPP 7.3.3
Pi 3B+
RF Plugin is reporting no updates, so I assume it's current as of today.

**Screenshots:**
![image](https://github.com/whitesoup12/remote-falcon/assets/5841728/0c8e019f-4e06-4686-a696-81ebd19385ff)

**Comment by whitesoup12** [comment]
This was fixed in plugin version 1.0.5.
