### ISSUE TITLE
clarity on usage of on-air vs off-air

### ISSUE THREAD

**Issue by lewislawrence2** [whitesoup12/remote-falcon#138]
**Your Show Name:**
empire lights

**Describe the bug:**
its not clear in the documentation how on-air and off-air work.  Currently my webpage always displays on-air.  last year it seems that the webpage toggled back and forth.  i don't think we are supposed to create a schedule for the remote falcon playlist.  can you please provide a bit of background as to how it works.  

**To Reproduce:**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior:**

**Screenshots:**

**Desktop (if issue is seen on desktop, otherwise N/A):**
 - OS: [e.g. Windows]

**Smartphone (if issue is seen on mobile, otherwise N/A):**

**Comment by whitesoup12** [comment]
https://docs.remotefalcon.com/docs/fpp-plugin/fpp-plugin-setup#turn-viewer-control-onoff
