### ISSUE TITLE
Super easy jukebox request with an added benefit!

### ISSUE THREAD

**Issue by PiXeL-Paradise-USA** [whitesoup12/remote-falcon#140]
Could a checkbox be added to limit the total number of song requests from a particular user? I much prefer the jukebox method over the voting, but adding a feature to limit each connection to say 1 or 2 songs would prevent interrupting the playlist excessively, and also allow others to grab a spot in the "Jukebox Queue Depth". This could also have a timeout setting like 30 minutes or 24 hours etc that the show owner could set (Each person can only choose 1 song per x amount of minutes)

As an added benefit, for those who have found the "Check Viewer Present" option to not be a functional solution due to browser security settings blocking those connections (essentially preventing remote falcon from working at all), setting a sequence limit and timeout on each connection could prevent someone from manipulating your show to the extreme, while away. 

Thank you so much for your consideration! This would be the icing on the cake for our show to prevent one car from loading up the queue, and not have to go to the voting method where that person would still have input at each voting cycle.

**Comment by whitesoup12** [comment]
This is part of #82
