### ISSUE TITLE
Unable to Modify Show Location

### ISSUE THREAD

**Issue by kentstroker** [whitesoup12/remote-falcon#29]
**Your Show Name:**
4040house

**Describe the bug:**
When trying to set the lat and lon, once you press enter or tab from the first field, it applies the update. When attempting then to set on, the lat gets reset back to previous setting.

**To Reproduce:**
On Show Location, change the Lat entry and note it gets applied
Now, try to set the lon to something new.
Notice how lat gets reset back to the default location.
It is not possible to update lat and lon both, one of the two always gets reset.

**Expected behavior:**
After updating both, then apply the changes once. Or, disable the default location from being applied.

**Comment by whitesoup12** [comment]
Fixed with merge #32.
