### ISSUE TITLE
Add the ability to sort sequences

### ISSUE THREAD

**Issue by DomDomDom13** [whitesoup12/remote-falcon#44]
**Is your feature request related to a problem? Please describe:**
No Problem

**Describe the solution you'd like:**
It would be nice to sort the sequences by Name, Duration, Artist, Category, Statistics (most requested), etc. by Ascending, Descending, or manual drag and drop. Currently this needs to be done on the FPP playlist side - which is also lacking some auto-sorting features.
As songs are added throughout the season it would be nice to have the feature so it is more organized for the viewer.

**Comment by chuckackerman** [comment]
I'd like this also.  Maybe not for the consumer to sort, but for me to be able to automatically sort.
