### ISSUE TITLE
Interrupt Schedule quirk

### ISSUE THREAD

**Issue by JRTRED** [whitesoup12/remote-falcon#46]
**Your Show Name:**
Wesley Lights

**Describe the bug:**
When the FPP APInis called to insert a playlist immediately, the plugin attempts to do so at the very last second to prevent the current requested sequence from getting interrupted. Turns out there’s a bit of a delay and FPP quickly goes back to the schedule before playing the next sequence. I might have a solution for that if you want to put a bug in for it.

**To Reproduce:**
1. Interrupt Schedule Enables
2. Request Multiple Songs
3. Song will play then after jump back to original schedule playlist quickly
4. Then play requested song that was next

**Expected behavior:**
Playlist should play in order without Hiccup

**Screenshots:**

**Desktop (if issue is seen on desktop, otherwise N/A):**
 - OS: n/a
 - Browser n/a

**Smartphone (if issue is seen on mobile, otherwise N/A):**
 - Device: n/a
 - Browser n/a

**Comment by whitesoup12** [comment]
So I've been testing a workaround and seems I may have found something that works. Try setting the `FPP Status Check Time` value to `0.5`. What this does is cause the RF listener in FPP to check your FPP status and for new requests every half second. I've found that the quicker checks allow the next sequence to queue up quicker, preventing the quick transition to the schedule then to the new request.

**Comment by JRTRED** [comment]
So when I try to do that, it sets it to 0 after restarting listener?

**Comment by whitesoup12** [comment]
> So when I try to do that, it sets it to 0 after restarting listener?

Yeah, good callout. The input fields were still parsing an integer. I just pushed a fix for this in 1.0.3. 

https://github.com/whitesoup12/remote-falcon-plugin/pull/70

**Comment by JRTRED** [comment]
Just updating this, still has that hiccup even with it set to .5

**Comment by JRTRED** [comment]
yes restarted, and can you let me know how to get the logs
<img width="1547" alt="Screenshot 2023-10-16 at 8 10 03 PM" src="https://github.com/whitesoup12/remote-falcon/assets/89848391/85c34bb2-8149-4493-b621-efe8b9fe1ffb">

**Comment by JRTRED** [comment]
[remote-falcon-listener.log](https://github.com/whitesoup12/remote-falcon/files/13042095/remote-falcon-listener.log)

**Comment by whitesoup12** [comment]
These logs are still showing version 1.0.2. The latest version is 1.0.4. When you update, you should reboot (or even better, power cycle your Pi or BBB).

**Comment by JRTRED** [comment]
ok updated to current version and tested, same thing it blinks the previous schedule then goes to next in queue. Updated logs attached.
[remote-falcon-listener-2.log](https://github.com/whitesoup12/remote-falcon/files/13048409/remote-falcon-listener-2.log)

**Comment by whitesoup12** [comment]
This is fixed in FPP plugin version 1.0.5.
