### ISSUE TITLE
FPP OS 7.2 - Token won't save

### ISSUE THREAD

**Issue by jnpetersen** [whitesoup12/remote-falcon#48]
I just updated my raspberry pi to OS 7.2 and I went to add all my plugins back in and when trying to add my token it does say `Remote Token Saved` but then which tabbing to another field it states `Remote Token Missing`.  I tried refreshing the browser soon after it says saved, but it still comes back blank.

**Comment by whitesoup12** [comment]
Did you power cycle your Pi or BB after installing the plugin?
