### ISSUE TITLE
Capabilities missing or not working from API

### ISSUE THREAD

**Issue by focusedonsound** [whitesoup12/remote-falcon#70]
Christmas In Boonton Township
 Link to page where I am currently doing development - https://christmasinboontontwp.com/current-sequences/

**Describe the bug:**

1. Adding a song to queue returns a message of 'QUEUE_FULL'  Even when there is currently nothing in the queue
2. When a playlist is playing and I 'Get' - nextSequenceInQueue  The API returns  { "currentSequence": "YourSequenceName" }
3. There is no way to pull current vote rankings via the API.  So if I would like to display on my site that a song has received X votes I am not able to.
4. currentQueueDepth always returns a value of the maximum number of songs in queue vs either returning the list of sequence that are currently in the queue, or the number of tracks in queue.
5. Adding the ability via API to clear the queue.

**Comment by whitesoup12** [comment]
This has been fixed.
