### ISSUE TITLE
Included head line "/config.js" is perhaps in error?

### ISSUE THREAD

**Issue by derwin12** [whitesoup12/remote-falcon#77]
![image](https://github.com/whitesoup12/remote-falcon/assets/4643499/042b90a3-1852-4e30-ae1b-92ae85362d0d)

**Comment by whitesoup12** [comment]
Ahh, yeah. Something I forgot to remove. I don't think it affecting anything though, is it?

**Comment by derwin12** [comment]
I wasn't sure .. just noticed the error while debugging my css.

**Comment by whitesoup12** [comment]
Fixed in #78
