### ISSUE TITLE
Enhanced Sequence Information and Display

### ISSUE THREAD

**Issue by kentstroker** [whitesoup12/remote-falcon#86]
Please consider adding to the Sequence information an additional column for "Artist." When displayed on the Viewer Page, place the Artist below the song title in italics and in a smaller font size.

Currently, when I make the Sequence Display Name to be "Because I'm Santa - Dollyrats," it is often wider than a smartphone display and wraps to a second line in an inelegant fashion.  When the existing Display Name is set to "Because I'm Santa" and a new column for Artist set to "Dollyrats," it would be possible to control better how this appears in the Viewer Page with the Display Name above the Artist in the list.

**Comment by whitesoup12** [comment]
Kudos on this request. I think a lot of people will benefit from it.
