### ISSUE TITLE
When using Category feature, invisible setting is not honored if a sequence in the same category is set to be visible

### ISSUE THREAD

**Issue by br2083** [whitesoup12/remote-falcon#95]
**Your Show Name:**
lightsonventurepark

**Describe the bug:**
When using the Category feature, if even a single sequence is set to be visible, it overrides all other sequences of the same category to also be visible even though they're set to be invisible.

**To Reproduce:**
I added a group of sequences to a "Post Christmas" category and had them all marked as invisible. This worked fine on my viewer page. I toggled a single one of those sequences to be visible, refreshed the viewer page, and now all sequences in that category were shown on the viewer page.

**Expected behavior:**
To prioritize visible/invisible setting over the category.

**Comment by whitesoup12** [comment]
I can look into this. For the time being couldn't you just remove the category from the hidden sequences?

**Comment by br2083** [comment]
For my purposes, I'm going to have the entire category hidden until I make them all visible at the same time so it shouldn't be an issue for me. It was just something I stumbled upon while testing so figured I'd report it in case it helped someone else.

**Comment by whitesoup12** [comment]
Fixed in PR #120
