### ISSUE TITLE
FPP Command - PSA On/Off and Manage PSA On/Off

### ISSUE THREAD

**Issue by tlabus** [whitesoup12/remote-falcon#96]
Some playlists are repeat effect sequences for before and after show hours. It would be cool to have an option to either turn on/off PSA entirely, or just turn on/off Manage PSA in a similar fashion to being able to turn on/off Viewer Control. This would all the repeat effect sequences from have the PSA come on every X loops, but allow to have the managed PSA on diffferent playlists where you want it to play every X sequences.

Thank you so much!

**Comment by tlabus** [comment]
Also, I know that I could just have Viewer Control off, keeping that on would allow the capability of a user selecting a song while the effect loops is playing.

**Comment by whitesoup12** [comment]
This is available now in FPP plugin version 1.0.6.

**Comment by tlabus** [comment]
That was amazingly fast! I will test this out tonight. Thank you!
